### ISSUE TITLE
Could not find on hexo plugins

### ISSUE THREAD

**Issue by tcrowe** [piktaszuikis/hexo-deployer-netlify#4]
Good day!

I was looking for something like this here: https://hexo.io/plugins/

I did not find. Did I do something wrong or was it not published in yet?

**Comment by piktaszuikis** [comment]
I've added a pull request: https://github.com/hexojs/site/pull/673
Let's see if it will get accepted.

**Comment by tcrowe** [comment]
Solved! Thank you @piktaszuikis 👋

**Comment by piktaszuikis** [comment]
You are welcome, m8! XD
